"""empty message

Revision ID: 4103434725bc
Revises: c5ea715f01f0
Create Date: 2022-11-19 17:27:54.089264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4103434725bc'
down_revision = 'c5ea715f01f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_subreddits', 'subreddit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'users_subreddits', type_='foreignkey')
    op.drop_constraint(None, 'users_subreddits', type_='foreignkey')
    op.drop_column('users_subreddits', 'mod_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_subreddits', sa.Column('mod_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'users_subreddits', 'users', ['mod_id'], ['id'])
    op.create_foreign_key(None, 'users_subreddits', 'users', ['admin_id'], ['id'])
    op.alter_column('users_subreddits', 'subreddit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
